sb_application_name: parallel-spring-boot
sb_build_namespace: parallel-spring-boot-build
sb_dev_namespace: parallel-spring-boot-dev
sb_stage_namespace: parallel-spring-boot-stage
sb_prod_namespace: parallel-spring-boot-prod
sb_application_repository_url: "https://github.com/redhat-cop/spring-rest.git"
sb_application_repository_ref: master
sb_application_readiness_response: "Hello, World!"
sb_application_readiness_path: "/v1/greeting"
sb_sa_name: "jenkins"
sb_source_repository_url: "https://github.com/briantward/container-pipelines.git"
sb_source_repository_ref: parallel-spring-boot-btw
sb_pipeline_script: "Jenkinsfile"

openshift_cluster_content:
- object: projects
  content:
  - name: "create environments"
    file: "{{ inventory_dir }}/../.openshift/projects/projects.yml"
    action: create
    tags:
      - project
- object: builds
  content:
  - name: "deploy build pipeline to dev"
    template: "{{ inventory_dir }}/../.openshift/templates/build.yml"
    params_from_vars:
      APPLICATION_NAME: "{{ sb_application_name }}"
      NAMESPACE: "{{ sb_build_namespace }}"
      SOURCE_REPOSITORY_URL: "{{ sb_source_repository_url }}"
      SOURCE_REPOSITORY_REF: "{{ sb_source_repository_ref }}"
      APPLICATION_SOURCE_REPO: "{{ sb_application_repository_url }}"
      APPLICATION_SOURCE_REF: "{{ sb_application_repository_ref }}"
      PIPELINE_SCRIPT: "{{ sb_pipeline_script }}"
    tags:
      - build
- object: deployments
  content:
  - name: "deploy dev environment"
    template: "{{ inventory_dir }}/../.openshift/templates/deployment.yml"
    params_from_vars:
      APPLICATION_NAME: "{{ sb_application_name }}"
      NAMESPACE: "{{ sb_dev_namespace }}"
      SA_NAMESPACE: "{{ sb_build_namespace }}"
      READINESS_RESPONSE: "{{ sb_application_readiness_response }}"
      READINESS_PATH: "{{ sb_application_readiness_path }}"
    tags:
      - deployment
  - name: "deply stage environment"
    template: "{{ inventory_dir }}/../.openshift/templates/deployment.yml"
    params_from_vars:
      APPLICATION_NAME: "{{ sb_application_name }}"
      NAMESPACE: "{{ sb_stage_namespace }}"
      SA_NAME: "{{ sb_sa_name }}"
      SA_NAMESPACE: "{{ sb_build_namespace }}"
      READINESS_RESPONSE: "{{ sb_application_readiness_response }}"
      READINESS_PATH: "{{ sb_application_readiness_path }}"
    tags:
      - deployment
  - name: "deply prod environment"
    template: "{{ inventory_dir }}/../.openshift/templates/deployment.yml"
    params_from_vars:
      APPLICATION_NAME: "{{ sb_application_name }}"
      NAMESPACE: "{{ sb_prod_namespace }}"
      SA_NAME: "{{ sb_sa_name }}"
      SA_NAMESPACE: "{{ sb_build_namespace }}"
      READINESS_RESPONSE: "{{ sb_application_readiness_response }}"
      READINESS_PATH: "{{ sb_application_readiness_path }}"
    tags:
      - deployment
